### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by jsgv** [pusher/pusher-websocket-go#23]
Connection does not stay open, nor does it try to reconnect.
Delaying execution with a `time.Sleep()` does allow me to see some events.

Is there something I am missing, or is that a feature that does not work yet?
Readme mentioned that it connected and reconnected.

```
client := pusher.New("<key>")
channel := client.Subscribe("<channel>")
channel.Bind("<event>", func(data interface{}) {
    fmt.Println(data)
})

time.Sleep(10 * time.Second)
```

**Comment by kn100** [comment]
In order for Pusher to maintain an open connection, you'll need to keep your code running somehow. Have a read: https://blog.sgmansfield.com/2016/06/how-to-block-forever-in-go/
